# Generated by Django 4.2.4 on 2023-12-31 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_course_serie_chapiter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='file',
        ),
        migrations.AddField(
            model_name='serie',
            name='url',
            field=models.URLField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 16, 8, 9, 904952, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 31, 16, 8, 9, 920672, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
    ]
