# Generated by Django 4.2.4 on 2024-01-01 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_serie_file_serie_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction',
            name='file',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='url',
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 9, 47, 4, 179962, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 9, 47, 4, 179962, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
    ]
