# Generated by Django 4.2.4 on 2024-01-01 09:58

import content.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_correction_file_remove_serie_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 9, 58, 8, 98596, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 9, 58, 8, 98596, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
        migrations.CreateModel(
            name='SeriePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to=content.models.upload_to)),
                ('number', models.IntegerField()),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.serie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorrectionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to=content.models.upload_to)),
                ('number', models.IntegerField()),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.correction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
