# Generated by Django 4.2.4 on 2023-12-29 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_serie_students_complete_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 18, 23, 0, 970666, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 29, 18, 23, 0, 970666, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
        migrations.AlterField(
            model_name='serie',
            name='students_complete_content',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_series', to='content.student'),
        ),
        migrations.AlterField(
            model_name='video',
            name='students_complete_content',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_videos', to='content.student'),
        ),
    ]
