# Generated by Django 4.2.4 on 2024-01-01 11:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0005_alter_codeverification_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField(db_comment='Comment content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(db_comment='Comment author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_type_comments', to='contenttypes.contenttype')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='SummaryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='')),
                ('number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='seriecomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='seriecomment',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='summarycomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='summarycomment',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='videocomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='videocomment',
            name='video',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='file',
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 11, 40, 7, 97537, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 11, 40, 7, 113162, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
        migrations.AlterField(
            model_name='seriepage',
            name='content',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='CorrectionComment',
        ),
        migrations.DeleteModel(
            name='SerieComment',
        ),
        migrations.DeleteModel(
            name='SummaryComment',
        ),
        migrations.DeleteModel(
            name='VideoComment',
        ),
        migrations.AddField(
            model_name='summarypage',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.summary'),
        ),
    ]
