# Generated by Django 4.2.4 on 2024-01-06 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_codeverification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapiter',
            name='levels',
            field=models.ManyToManyField(related_name='chapiter_levels', to='content.level'),
        ),
        migrations.AddField(
            model_name='course',
            name='levels',
            field=models.ManyToManyField(related_name='cours_levels', to='content.level'),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 10, 46, 15, 620100, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 6, 10, 46, 15, 620100, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
    ]
