# Generated by Django 4.2.4 on 2023-12-29 18:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_serie_students_complete_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='students_complete_content',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_series', to='content.student'),
        ),
        migrations.AddField(
            model_name='video',
            name='students_complete_content',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_videos', to='content.student'),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 18, 29, 1, 942800, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='correction',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 29, 18, 29, 1, 942800, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
        migrations.AlterField(
            model_name='serie',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
