# Generated by Django 4.2.4 on 2024-01-01 12:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_rename_sirie_correction_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='teacher',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 12, 7, 47, 532930, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='correctionpage',
            name='content',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 12, 7, 47, 532930, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
    ]
