# Generated by Django 4.2.4 on 2023-12-29 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_codeverification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 18, 50, 42, 919092, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 29, 18, 50, 42, 919092, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
        migrations.AlterOrderWithRespectTo(
            name='correction',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='serie',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='summary',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='video',
            order_with_respect_to=None,
        ),
    ]
