# Generated by Django 4.2.4 on 2024-01-01 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_attachment_video_attachment_correction_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachment',
            new_name='AttachmentCorrection',
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 12, 42, 7, 21984, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 12, 42, 7, 21984, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
        migrations.CreateModel(
            name='AttachmentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttachmentSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.serie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
