# Generated by Django 4.2.4 on 2024-01-07 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_codeverification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 16, 44, 5, 682397, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 16, 44, 5, 692510, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('exercice', 'exercice'), ('course', 'course')], max_length=100),
        ),
    ]
