# Generated by Django 4.2.4 on 2024-01-01 20:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_serie_file_alter_codeverification_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('chapiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.chapiter')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='attachmentserie',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='chapiter',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='video',
            name='chapiter',
        ),
        migrations.RemoveField(
            model_name='video',
            name='teacher',
        ),
        migrations.AddField(
            model_name='correction',
            name='file',
            field=models.FileField(default=1, upload_to='pdf_files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 20, 24, 8, 42063, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 20, 24, 8, 42063, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
        migrations.AlterField(
            model_name='serie',
            name='file',
            field=models.FileField(upload_to='pdf_files'),
        ),
        migrations.DeleteModel(
            name='AttachmentCorrection',
        ),
        migrations.DeleteModel(
            name='AttachmentSerie',
        ),
        migrations.AddField(
            model_name='serie',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summary',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course'),
        ),
    ]
