# Generated by Django 4.1 on 2024-06-18 14:43

import content.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_remove_correction_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction',
            name='id',
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 14, 42, 59, 912471, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='correction',
            name='file',
            field=models.FileField(upload_to=content.models.upload_correction_to),
        ),
        migrations.AlterField(
            model_name='correction',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='content.contentdocument'),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 18, 14, 42, 59, 928089, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
    ]
