# Generated by Django 4.1 on 2024-06-18 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_correction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 14, 43, 55, 115364, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='correction',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.contentdocument', unique=True),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 18, 14, 43, 55, 130979, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
    ]
