# Generated by Django 4.2.4 on 2024-01-10 18:51

import content.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_codeverification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='code',
            field=models.CharField(editable=False, error_messages={'invalid': 'Invalid code format. Please use alphanumeric characters only.', 'max_length': 'The code is too long. Please use up to %(max)d characters.', 'unique': 'This code is already in use. Please choose a different code.'}, max_length=255, unique=True, validators=[content.models.validate_alphanumeric_code]),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 18, 51, 54, 158995, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 18, 51, 54, 158995, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
    ]
