# Generated by Django 4.2.4 on 2024-01-15 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_video_status_alter_codeverification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='levels',
            field=models.ManyToManyField(related_name='course_levels', to='content.level'),
        ),
        migrations.AddField(
            model_name='subject',
            name='levels',
            field=models.ManyToManyField(related_name='level_subjects', to='content.level'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='levels',
            field=models.ManyToManyField(related_name='level_videos', to='content.level'),
        ),
        migrations.AddField(
            model_name='video',
            name='offers',
            field=models.ManyToManyField(related_name='offer_videos', to='content.offer'),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 16, 15, 42, 470088, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 15, 16, 15, 42, 470088, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
    ]
