# Generated by Django 5.0.1 on 2024-02-03 13:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_alter_chapiter_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapiter',
            name='description',
            field=models.TextField(db_index=True, error_messages={'blank': 'The description cannot be left blank.'}),
        ),
        migrations.AlterField(
            model_name='chapiter',
            name='subject',
            field=models.ForeignKey(error_messages={'blank': 'Please select a subject.'}, on_delete=django.db.models.deletion.PROTECT, to='content.subject'),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 13, 9, 31, 223291, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 13, 9, 31, 237317, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
    ]
