# Generated by Django 5.0.6 on 2024-07-01 19:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_remove_contentdocument_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdocument',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.contentdocument'),
        ),
        migrations.AddField(
            model_name='contentdocument',
            name='type',
            field=models.CharField(choices=[('serie', 'serie'), ('summary', 'summary'), ('correction', 'correction')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 19, 19, 21, 720403, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='getoffer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 1, 19, 19, 21, 725511, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'Invalid date format. Please provide a valid date.'}),
        ),
    ]
